### ISSUE TITLE
Doesn't work with Ubuntu 16.04

### ISSUE THREAD

**Issue by andrade209** [nunofernandes/icingaweb2-module-ca#3]
No Information is shown in the webinterface.

## Expected Behavior
Pending certificates should be shown.

## Current Behavior
I can't see the actual pending certificate requests. 

## Possible Solution
Maybe the username oder path is not correct.

## Steps to Reproduce (for bugs)
Use the configuration shown in the readme. 

## Context
I tried to figure out, if the pathes oder usernames are different on Ubuntu, but I can't solve the problem.

## Your Environment

* Icinga Web 2 version and modules (System - About): 
* Version used (`icinga2 --version`):  r2.8.2-1
* Operating System and version: Ubuntu 16.04.4 LTS
* Enabled features (`icinga2 feature list`): Enabled features: api checker command graphite ido-mysql mainlog notification
* Config validation (`icinga2 daemon -C`): information/cli: Icinga application loader (version: r2.8.2-1)
information/cli: Loading configuration file(s).
information/ConfigItem: Committing config item(s).
information/ApiListener: My API identity: icinga2.myhome.local
information/ConfigItem: Instantiated 1 ApiListener.
information/ConfigItem: Instantiated 105 Zones.
information/ConfigItem: Instantiated 104 Endpoints.
information/ConfigItem: Instantiated 1 FileLogger.
information/ConfigItem: Instantiated 2 ApiUsers.
information/ConfigItem: Instantiated 2408 Notifications.
information/ConfigItem: Instantiated 12 NotificationCommands.
information/ConfigItem: Instantiated 246 CheckCommands.
information/ConfigItem: Instantiated 1 Downtime.
information/ConfigItem: Instantiated 22 HostGroups.
information/ConfigItem: Instantiated 1 IcingaApplication.
information/ConfigItem: Instantiated 1 EventCommand.
information/ConfigItem: Instantiated 120 Hosts.
information/ConfigItem: Instantiated 1 Comment.
information/ConfigItem: Instantiated 1 UserGroup.
information/ConfigItem: Instantiated 8 Users.
information/ConfigItem: Instantiated 3 TimePeriods.
information/ConfigItem: Instantiated 1032 Services.
information/ConfigItem: Instantiated 30 ServiceGroups.
information/ConfigItem: Instantiated 1 ScheduledDowntime.
information/ConfigItem: Instantiated 1 CheckerComponent.
information/ConfigItem: Instantiated 1 ExternalCommandListener.
information/ConfigItem: Instantiated 1 GraphiteWriter.
information/ConfigItem: Instantiated 1 IdoMysqlConnection.
information/ConfigItem: Instantiated 1 NotificationComponent.
information/ScriptGlobal: Dumping variables to file '/var/cache/icinga2/icinga2.vars'
information/cli: Finished validating the configuration file(s).

**Comment by nunofernandes** [comment]
Hello,

Can you please post the output of the following commands:

1) check which user is running the webserver
`$ ps fax | grep -E '(http|apache)'`

2) list the content of the sudoers
`$ ls -la /etc/sudoer*`

3) get the module config file
`$ cat /etc/icingaweb2/modules/ca/config.ini`

4) check which user is running icinga
`$ ps fax | grep icinga`

5) Whereis sudo
`$ which sudo`

Thanks,
Nuno Fernandes

**Comment by nunofernandes** [comment]
Ahh... and also

6. Are there certificates to sign?
`icinga2 ca list`

**Comment by andrade209** [comment]
Hi,
thanks for your help! Mabye my linux skills aren't goog enouph.

1. ps fax | grep -E '(http|apache)'
16634 pts/0    S+     0:00          \_ grep --color=auto -E (http|apache)
 1410 ?        Ss     0:19 /usr/sbin/apache2 -k start
 1449 ?        S      0:05  \_ /usr/sbin/apache2 -k start
 8845 ?        S      0:04  \_ /usr/sbin/apache2 -k start
12263 ?        S      0:02  \_ /usr/sbin/apache2 -k start
15105 ?        S      0:02  \_ /usr/sbin/apache2 -k start
15286 ?        S      0:02  \_ /usr/sbin/apache2 -k start
15292 ?        S      0:02  \_ /usr/sbin/apache2 -k start
23504 ?        S      0:02  \_ /usr/sbin/apache2 -k start
23936 ?        S      0:00  \_ /usr/sbin/apache2 -k start
24856 ?        S      0:00  \_ /usr/sbin/apache2 -k start
25335 ?        S      0:00  \_ /usr/sbin/apache2 -k start

2. ls -la /etc/sudoer*
-r--r----- 1 root root  755 Apr  4 11:38 /etc/sudoers
/etc/sudoers.d:
total 16
drwxr-xr-x   2 root root 4096 Apr  4 11:38 .
drwxr-xr-x 111 root root 4096 Apr  4 11:38 ..
-r--r-----   1 root root  256 Apr  4 11:38 apache2
-r--r-----   1 root root  958 Mär 30  2016 README

3. cat /etc/icingaweb2/modules/ca/config.ini
[config]
runas = "icinga2"
sudo = "/usr/bin/sudo"
icinga2 = "/usr/lib/icinga2/icinga2"

4. ps fax | grep icinga
23102 pts/0    S+     0:00          \_ grep --color=auto icinga
25448 ?        Ssl    2:35 /usr/lib/x86_64-linux-gnu/icinga2/sbin/icinga2 --no-stack-rlimit daemon -e $ICINGA2_LOG_DIR/error.log --reload-internal 25028
25461 ?        S      0:05  \_ /usr/lib/x86_64-linux-gnu/icinga2/sbin/icinga2 --no-stack-rlimit daemon -e $ICINGA2_LOG_DIR/error.log --reload-internal 25028

5. which sudo
/usr/bin/sudo

6. icinga2 ca list
Finge        | Timestamp                         | Signed | Subject
-----------|-----------------------------|------ -|--------
4...522702 | Apr  4 05:59:15 2018 GMT |        | CN = openvas.myhome.local
e....c4e9d5 | Apr  4 06:00:03 2018 GMT | *      | CN = openvas.myhome.local

**Comment by nunofernandes** [comment]
Hello,

I made a mistake in the 1 and 4.
Please rerun with:

1. `ps faxu | grep -E '(http|apache)' `

4. `ps faxu | grep icinga`

**Comment by andrade209** [comment]
Hi,
 ps faxu | grep -E '(http|apache)'
root     30857  0.0  0.0  14472   972 pts/0    S+   11:59   0:00          \_ grep --color=auto -E (http|apache)
root      1410  0.0  0.5 492676 41324 ?        Ss   Apr03   0:19 /usr/sbin/apache2 -k start
www-data  1449  0.0  0.5 574480 43852 ?        S    08:11   0:05  \_ /usr/sbin/apache2 -k start
www-data  8845  0.0  0.5 574528 45556 ?        S    09:48   0:04  \_ /usr/sbin/apache2 -k start
www-data 12263  0.0  0.5 574468 42156 ?        S    09:56   0:02  \_ /usr/sbin/apache2 -k start
www-data 15105  0.0  0.5 574596 43992 ?        S    10:03   0:03  \_ /usr/sbin/apache2 -k start
www-data 15292  0.0  0.5 573504 41948 ?        S    10:03   0:03  \_ /usr/sbin/apache2 -k start
www-data 23936  0.0  0.4 574300 40868 ?        S    10:23   0:00  \_ /usr/sbin/apache2 -k start
www-data 24856  0.0  0.4 573412 37528 ?        S    10:25   0:00  \_ /usr/sbin/apache2 -k start
www-data 25335  0.0  0.4 573452 38900 ?        S    10:26   0:00  \_ /usr/sbin/apache2 -k start
www-data 17515  0.0  0.3 499456 31280 ?        S    11:26   0:00  \_ /usr/sbin/apache2 -k start
www-data 17814  0.0  0.3 498648 28328 ?        S    11:27   0:00  \_ /usr/sbin/apache2 -k start

 ps faxu | grep icinga
root     31045  0.0  0.0  14472   988 pts/0    S+   12:00   0:00          \_ grep --color=auto icinga
nagios   25448  3.5  0.9 4397188 80840 ?       Ssl  10:26   3:17 /usr/lib/x86_64-linux-gnu/icinga2/sbin/icinga2 --no-stack-rlimit daemon -e $ICINGA2_LOG_DIR/error.log --reload-internal 25028
nagios   25461  0.1  0.0 513876  5584 ?        S    10:26   0:07  \_ /usr/lib/x86_64-linux-gnu/icinga2/sbin/icinga2 --no-stack-rlimit daemon -e $ICINGA2_LOG_DIR/error.log --reload-internal 25028

**Comment by nunofernandes** [comment]
Ok.. for what i see, it is the configuration that is wrong. Your icinga2 is running with the user nagios and the webserver is running as www-data.

1. Please change the /etc/icingaweb2/modules/ca/config.ini to:
```
[config]
runas = "nagios"
sudo = "/usr/bin/sudo"
icinga2 = "/usr/lib/icinga2/icinga2"
```

2. Please change /etc/sudoers/apache2 to:
```
Cmnd_Alias      CA_CMDS = /usr/lib/icinga2/icinga2 ca list, /usr/lib/icinga2/icinga2 ca sign *
Cmnd_Alias      APACHE_COMMANDS = CA_CMDS
User_Alias      APACHEUSERS = www-data

Defaults:APACHEUSERS        !requiretty
APACHEUSERS   ALL = (nagios) NOPASSWD: APACHE_COMMANDS
```

And try using the module in the web interface.

Thanks,
Nuno Fernandes

**Comment by andrade209** [comment]
Thanks! I changed both configurations, but the module in webinterface is still empty

**Comment by nunofernandes** [comment]
Can you please output the result of:

`# su - www-data -s /bin/bash`
`www-data$   /usr/bin/sudo -u nagios /usr/lib/icinga2/icinga2 ca list`

**Comment by andrade209** [comment]
su - www-data -s /bin/bash
www-data@icinga2:~$ /usr/bin/sudo -u nagios /usr/lib/icinga2/icinga2 ca list
sudo: /usr/lib/icinga2/icinga2: command not found
www-data@icinga2:~$ /usr/bin/sudo -u nagios /usr/lib/icinga2 ca list
[sudo] password for www-data:

**Comment by nunofernandes** [comment]
hum.. ok.. whereis your icinga binary?

`find / -type f -iname icinga2`

**Comment by andrade209** [comment]
find / -type f -iname icinga2
/usr/share/bash-completion/completions/icinga2
/usr/lib/x86_64-linux-gnu/icinga2/sbin/icinga2
/usr/lib/icinga2/icinga2
/usr/sbin/icinga2
/etc/logrotate.d/icinga2
/etc/init.d/icinga2
/etc/default/icinga2

**Comment by nunofernandes** [comment]
Hello,

1. Please change the /etc/icingaweb2/modules/ca/config.ini to:
```
[config]
runas = "nagios"
sudo = "/usr/bin/sudo"
icinga2 = "/usr/sbin/icinga2"
```

2. Please change /etc/sudoers/apache2 to:
```
Cmnd_Alias      CA_CMDS =  /usr/sbin/icinga2 ca list,  /usr/sbin/icinga2 ca sign *
Cmnd_Alias      APACHE_COMMANDS = CA_CMDS
User_Alias      APACHEUSERS = www-data

Defaults:APACHEUSERS        !requiretty
APACHEUSERS   ALL = (nagios) NOPASSWD: APACHE_COMMANDS
```

Next, before trying the web interface, please try again the commands:

```
# su - www-data -s /bin/bash
www-data$ /usr/bin/sudo -u nagios /usr/sbin/icinga2 ca list
```

**Comment by andrade209** [comment]
Thank you very much for your patience! It works!

**Comment by nunofernandes** [comment]
Glad to hear that! I will close this issue then.
