### ISSUE TITLE
Address changes in Icinga 2 2.11

### ISSUE THREAD

**Issue by dgoetz** [nunofernandes/icingaweb2-module-ca#6]
I want to make you aware of an upcoming change in Icinga 2 2.11 which will affect your module.
* https://github.com/Icinga/icinga2/pull/7026
* https://github.com/Icinga/icinga2/pull/7046/files
No release date announced yet.

## Expected Behavior
Handle the new behaviour coming with 2.11:
* `icinga2 ca list` will only list unsigned requests.
* `icinga2 ca list --all` will list all requests.
* Icinga 2 will cleanup unsigned requests after 1 week.

## Current Behavior
Without addressing the changes the module will only show unsigned requests.

## Possible Solution
Just add `--all` to the command or add a config option for it.

## Context
Icinga 2 2.11 coming later this year.

**Comment by nunofernandes** [comment]
Thanks for the heads up! I will maintain this issue open until 2.11 is released and in the meantime I will try to add the logic to check what is the installed version and work with it.

**Comment by nunofernandes** [comment]
Should now be fixed in the latest release. Please let me know if it working. Please note that you need to update the sudoers configuration file, something like:
```
Cmnd_Alias      CA_CMDS = /usr/sbin/icinga2 ca list, /usr/sbin/icinga2 ca sign *
```
to
```
Cmnd_Alias      CA_CMDS = /usr/sbin/icinga2 ca list, /usr/sbin/icinga2 ca sign *, /usr/sbin/icinga2 ca list --all
```

**Comment by nunofernandes** [comment]
Closing this as I didn't receive any reports with issues.
